/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Datos.DRecibos;
import Logica.LRecibos;
import Principal.DetalleRecibos;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo
 */
public class FrmRecibos extends javax.swing.JInternalFrame {

    /**
     * Creates new form DetalleRecibos
     */
    public FrmRecibos() {
        initComponents();
        mostrarRecibos();
    }
    public void buscarRecibos(int id) {
        DefaultTableModel miModelo;
        LRecibos fun = new LRecibos();
        DRecibos dts = new DRecibos();
        dts.setIdRecibo(id);
        miModelo = fun.buscarRecibos(dts);
        tblRecibos.setModel(miModelo);
    }    
    public void mostrarRecibos() {
        DefaultTableModel miModelo;
        LRecibos fun = new LRecibos();
        miModelo = fun.mostrarRecibos(null);
        tblRecibos.setModel(miModelo);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecibos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Recibos"));

        tblRecibos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FECHA", "PERSONA ENTREGA", "PERSONA RECIBE"
            }
        ));
        tblRecibos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblRecibosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblRecibos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRecibosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRecibosMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            String idrecibo = tblRecibos.getValueAt(tblRecibos.getSelectedRow(), 0).toString();
            String fecha = tblRecibos.getValueAt(tblRecibos.getSelectedRow(), 1).toString();
            String pentrega = tblRecibos.getValueAt(tblRecibos.getSelectedRow(), 2).toString();
            String precibe = tblRecibos.getValueAt(tblRecibos.getSelectedRow(), 3).toString();
            

            DetalleRecibos mi = new DetalleRecibos(new JFrame(), true);
            
            mi.setFactura(idrecibo,fecha,pentrega,precibe);
            mi.setLocationRelativeTo(null);
            mi.setVisible(true);
        }
    }//GEN-LAST:event_tblRecibosMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRecibos;
    // End of variables declaration//GEN-END:variables
}
