/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Eduardo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        ImageIcon icFacturas = new ImageIcon(getClass().getResource("/Imagenes/1052890.png"));
        Icon iconoFac = new ImageIcon(icFacturas.getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
        btnFacturas.setIcon(iconoFac);

        ImageIcon icRecibos = new ImageIcon(getClass().getResource("/Imagenes/computer-icons-receipt-invoice-accounting-receipt-png-clip-art.png"));
        Icon iconoRec = new ImageIcon(icRecibos.getImage().getScaledInstance(130, 80, Image.SCALE_DEFAULT));
        btnRecibos.setIcon(iconoRec);

        ImageIcon icAlmacen = new ImageIcon(getClass().getResource("/Imagenes/warehouse-transport-logistics-order-fulfillment-warehouse.jpg"));
        Icon iconoAlm = new ImageIcon(icAlmacen.getImage().getScaledInstance(75, 75, Image.SCALE_DEFAULT));
        btnAlmacen.setIcon(iconoAlm);

        timer.start();

    }
    // Fecha y Hora correspondientes.
    Timer timer = new Timer(1000, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            Calendar cal = new GregorianCalendar();
            int hh, mm, ss, dia, mes, aa;
            hh = cal.get(Calendar.HOUR);
            ss = cal.get(Calendar.SECOND);
            mm = cal.get(Calendar.MINUTE);

            dia = cal.get(Calendar.DAY_OF_MONTH);
            mes = cal.get(Calendar.MONTH);
            aa = cal.get(Calendar.YEAR);

            lblHora.setText(hh + ":" + mm + ":" + ss);
            lblFecha.setText(dia + "/" + (mes + 1) + "/" + aa);
        }
    });

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnFacturas = new javax.swing.JButton();
        btnRecibos = new javax.swing.JButton();
        btnAlmacen = new javax.swing.JButton();
        dpnEscritorio = new javax.swing.JDesktopPane();
        lblFecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemFacturas = new javax.swing.JMenuItem();
        itemDetalleRecibos = new javax.swing.JMenuItem();
        itemHerramientas = new javax.swing.JMenu();
        itemUsuarios = new javax.swing.JMenuItem();
        itemProveedores = new javax.swing.JMenuItem();
        ItemDepartamentos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnFacturas.setText("Facturas");
        btnFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturasActionPerformed(evt);
            }
        });

        btnRecibos.setText("Recibos");
        btnRecibos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecibosActionPerformed(evt);
            }
        });

        btnAlmacen.setText("Almacén");
        btnAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
            .addComponent(btnRecibos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRecibos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblFecha.setText("jLabel6");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Hora:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Fecha:");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        lblHora.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblHora.setText("jLabel5");

        javax.swing.GroupLayout dpnEscritorioLayout = new javax.swing.GroupLayout(dpnEscritorio);
        dpnEscritorio.setLayout(dpnEscritorioLayout);
        dpnEscritorioLayout.setHorizontalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpnEscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addComponent(lblUsuario)
                    .addComponent(lblHora))
                .addContainerGap(777, Short.MAX_VALUE))
        );

        dpnEscritorioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, lblFecha, lblHora, lblUsuario});

        dpnEscritorioLayout.setVerticalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpnEscritorioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblFecha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dpnEscritorio.setLayer(lblFecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnEscritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnEscritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnEscritorio.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnEscritorio.setLayer(lblUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpnEscritorio.setLayer(lblHora, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("Consultas");

        itemFacturas.setText("Detalle de Facturas");
        itemFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFacturasActionPerformed(evt);
            }
        });
        jMenu1.add(itemFacturas);

        itemDetalleRecibos.setText("Detalle de Recibos");
        itemDetalleRecibos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDetalleRecibosActionPerformed(evt);
            }
        });
        jMenu1.add(itemDetalleRecibos);

        jMenuBar1.add(jMenu1);

        itemHerramientas.setText("Herramientas");

        itemUsuarios.setText("Usuarios");
        itemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuariosActionPerformed(evt);
            }
        });
        itemHerramientas.add(itemUsuarios);

        itemProveedores.setText("Proveedores");
        itemProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProveedoresActionPerformed(evt);
            }
        });
        itemHerramientas.add(itemProveedores);

        ItemDepartamentos.setText("Departamentos");
        ItemDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemDepartamentosActionPerformed(evt);
            }
        });
        itemHerramientas.add(ItemDepartamentos);

        jMenuBar1.add(itemHerramientas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dpnEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dpnEscritorio)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(76, 76, 76))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Método para abrir usuarios
    private void itemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuariosActionPerformed
        // TODO add your handling code here:
        Usuarios misUsuarios = new Usuarios();
        dpnEscritorio.add(misUsuarios);
        misUsuarios.show();
    }//GEN-LAST:event_itemUsuariosActionPerformed
    // Método para abrir proveedores
    private void itemProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProveedoresActionPerformed
        // TODO add your handling code here:
        Proveedores misProveedores = new Proveedores();
        dpnEscritorio.add(misProveedores);
        misProveedores.show();
    }//GEN-LAST:event_itemProveedoresActionPerformed
    // Método para abrir facturas
    private void btnFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturasActionPerformed
        // TODO add your handling code here:
        Facturas misFacturas = new Facturas();
        dpnEscritorio.add(misFacturas);
        misFacturas.show();
    }//GEN-LAST:event_btnFacturasActionPerformed
    // Método para abrir departamentos
    private void ItemDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemDepartamentosActionPerformed
        // TODO add your handling code here:
        Departamentos misDepartamentos = new Departamentos();
        dpnEscritorio.add(misDepartamentos);
        misDepartamentos.show();
    }//GEN-LAST:event_ItemDepartamentosActionPerformed
    // Método para abrir el detalle de facturas
    private void itemFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFacturasActionPerformed
        // TODO add your handling code here:
        FrmFacturas misFacturas = new FrmFacturas();
        dpnEscritorio.add(misFacturas);
        misFacturas.show();
    }//GEN-LAST:event_itemFacturasActionPerformed
    // Método para abrir detalle de recibos
    private void itemDetalleRecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDetalleRecibosActionPerformed
        // TODO add your handling code here:
        FrmRecibos misRecibos = new FrmRecibos();
        dpnEscritorio.add(misRecibos);
        misRecibos.show();
    }//GEN-LAST:event_itemDetalleRecibosActionPerformed
    // Método para abrir alamcen
    private void btnAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenActionPerformed
        // TODO add your handling code here:
        Almacen miAlmacen = new Almacen();
        dpnEscritorio.add(miAlmacen);
        miAlmacen.show();
    }//GEN-LAST:event_btnAlmacenActionPerformed
    // Método para abrir recibos
    private void btnRecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecibosActionPerformed
        // TODO add your handling code here:
        Recibos miRecibo = new Recibos();
        dpnEscritorio.add(miRecibo);
        miRecibo.show();
    }//GEN-LAST:event_btnRecibosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Se cambia la llamada a principal por la llamada al login.
                Login miLogin = new Login();
                miLogin.setLocationRelativeTo(null);
                miLogin.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemDepartamentos;
    private javax.swing.JButton btnAlmacen;
    private javax.swing.JButton btnFacturas;
    private javax.swing.JButton btnRecibos;
    private javax.swing.JDesktopPane dpnEscritorio;
    private javax.swing.JMenuItem itemDetalleRecibos;
    private javax.swing.JMenuItem itemFacturas;
    private javax.swing.JMenu itemHerramientas;
    private javax.swing.JMenuItem itemProveedores;
    private javax.swing.JMenuItem itemUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables

    void setDatos(String usuario, String perfil) {
        lblUsuario.setText(usuario);
    }
}
